### ISSUE TITLE
googIPv6 RTCConstraint not passed through to rtc.io mediaHandlerFactory

### ISSUE THREAD

**Issue by warrenjmcdonald** [rtc-io/rtc-sip#1]
When using the sip.js 6.4 with the rtc.io mediaHandlerFactory, the  {'googIPv6': 'false'}, RTCConstraint is not being used in the peer connection. Other constraints such as OffertoReceiveAudio/Video are being used correctly. 

 The same RTCConstraint object used with sip.js directly (no media factory), is working as expected.

See code extract of test harness below.

``` js
var userAgent = new aartc.SIP.UA({
    mediaHandlerFactory: aartc.mediaHandlerFactory({plugins: [aartc.pluginNictaIos]}),
    wsServers: ['wss://<servername>'],
    stunServers: ["<stunserver>"],
    turnServers: [
                {
                urls:["turn:<turnserver>:3478"],
                username:"#######",
                password:"########"
                }
                ],
    hackViaTcp: true,
    hackIpInContact: true,
    traceSip: true
  });


function startcall(){
    var options = {
                media:{
                     stream: Stream,
                         constraints: {
                                audio: true,
                                video: true
                                 }
                        },
                 RTCConstraints: {
                 "optional": [
                        {'DtlsSrtpKeyAgreement': 'true'},
                        {'OfferToReceiveVideo': 'true'},
                        {'googIPv6': 'false'},
                        {'OfferToReceiveAudio': 'true'}
                        ]
                                }
                        };

  session = userAgent.invite('sip:' + conf_id.value + '@<domainname>', options);
  session.on('accepted', onAccepted);
```

**Comment by warrenjmcdonald** [comment]
@DamonOehlman Any thoughts on this. This is a higher priority than the TURN creds expiry issues. We can skirt around this by not using the media handler. This will prevent use in iOS, but we still have other work to do there yet, so that may be OK.

**Comment by DamonOehlman** [comment]
@warrenjmcdonald I'll try and take a look at this tonight.  Shouldn't be too tricky to fix.

**Comment by DamonOehlman** [comment]
@warrenjmcdonald I've got no good explanation of why I did it, but for some reason I am specifically not passing through the options when creating a new peer connection object (see 08cfd6ff2ad9220908aa49018dc83f6d91ebc7a7)

I'll investigate reinstating that now.

**Comment by DamonOehlman** [comment]
I think this should now be fixed in `1.1.0` courtesy of d0f1c6979e80c4ac15145cc5d9b1fd2f274849fe

**Comment by warrenjmcdonald** [comment]
Thanks @DamonOehlman. We will test this ASAP.

**Comment by warrenjmcdonald** [comment]
This fix has passed testing. Thanks heaps.

Warren
